---
- name: Start Backend container using docker compose command
  ansible.builtin.shell:
    cmd: "docker compose -f /home/ubuntu/yolo/docker-compose.yaml up -d tim-backend"
    chdir: /home/ubuntu/yolo
  become: yes
  become_user: ubuntu

- name: Wait for Backend service to be healthy (via docker inspect)
  ansible.builtin.shell:
    cmd: "docker inspect --format='{% raw %}{{.State.Health.Status}}{% endraw %}' tim-backend"
    chdir: /home/ubuntu/yolo
  register: backend_health_check
  until: backend_health_check.stdout == 'healthy'
  retries: 30
  delay: 5
  become: yes
  become_user: ubuntu
