services:

  tim-client:
    image: timthoithi100/yolo-client:1.0.0
    build:
      context: ./client
      args:
            REACT_APP_API_URL: http://54.210.74.59:5000 
    container_name: tim-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      tim-backend:
        condition: service_healthy
    networks:
      - app-net

  tim-backend:
    image: timthoithi100/yolo-backend:1.0.0
    build: ./backend
    container_name: tim-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://app-mongo:27017/yolodb
    depends_on:
      app-mongo:
        condition: service_healthy
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app-mongo:
    image: mongo:4.4
    container_name: app-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db
    environment:
      - MONGO_INITDB_DATABASE=yolodb
    healthcheck:
      test: ["CMD", "bash", "-c", "mongo --eval 'quit(db.adminCommand(\"ping\").ok ? 0 : 1)'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/16

volumes:
  app-mongo-data:
    driver: local
