---
- name: Orchestrate AWS Infrastructure Provisioning and Application Deployment
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    terraform_dir: "{{ lookup('env', 'PWD') }}/terraform"
    aws_region: "us-east-1"
    key_pair_name: "yolo-key"
    public_key_path: "/home/tim/.ssh/id_rsa.pub"
