version: "3.8"

services:

  tim-client:
    image: timthoithi100/yolo-client:1.0.0
    build: ./client
    container_name: tim-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - tim-backend
    networks:
      - app-net

  tim-backend:
    image: timthoithi100/yolo-backend:1.0.0
    build: ./backend
    container_name: tim-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://app-ip-mongo:27017/yolodb
    depends_on:
      - app-ip-mongo
    networks:
      - app-net

  app-ip-mongo:
    image: mongo:latest
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db

networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/16

volumes:
  app-mongo-data:
    driver: local
