---
- name: Provision and Deploy Yolo Application
  hosts: ansible-target
  become: yes
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Wait for system to be ready
      ansible.builtin.wait_for_connection:
        timeout: 300

  roles:
    - role: common
      tags:
        - setup
        - common

    - role: mongo_db
      tags:
        - database
        - mongo

    - role: backend_app
      tags:
        - backend
        - deploy

    - role: frontend_app
      tags:
        - frontend
        - deploy

  post_tasks:
    - name: Inform about application access
      ansible.builtin.debug:
        msg: |
          The Yolo application should now be running.
          Access the frontend at http://127.0.0.1:3001
          Access the backend API at http://127.0.0.1:5000