---
- name: Ensure Git is installed
  ansible.builtin.apt:
    name: git
    state: present
  become: yes

- name: Clone the Yolo project repository
  ansible.builtin.git:
    repo: 'https://github.com/timthoithi100/yolo.git'
    dest: /home/ubuntu/yolo
    version: master
    single_branch: yes
    force: yes
  become: yes
  become_user: ubuntu
