---
- name: Copy docker-compose.yaml to the EC2 instance
  ansible.builtin.copy:
    src: "{{ lookup('env', 'PWD') }}/docker-compose.yaml"
    dest: /home/ubuntu/yolo/docker-compose.yaml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: yes

- name: Start MongoDB container using docker compose command
  ansible.builtin.shell:
    cmd: "docker compose -f /home/ubuntu/yolo/docker-compose.yaml up -d app-mongo"
    chdir: /home/ubuntu/yolo
  become: yes
  become_user: ubuntu

- name: Wait for MongoDB service to be healthy (via docker inspect)
  ansible.builtin.shell:
    cmd: "docker inspect --format='{{.State.Health.Status}}' app-mongo"
    chdir: /home/ubuntu/yolo
  register: mongo_health_check
  until: mongo_health_check.stdout == 'healthy'
  retries: 30
  delay: 5
  become: yes
  become_user: ubuntu
