---
- name: Copy docker-compose.yaml to the EC2 instance
  ansible.builtin.template:
    src: "{{ lookup('env', 'PWD') }}/docker-compose.yaml.j2"
    dest: /home/ubuntu/yolo/docker-compose.yaml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: yes

- name: Pull MongoDB image
  ansible.builtin.shell:
    cmd: "docker pull mongo:4.4"
  become: yes
  become_user: ubuntu

- name: Start MongoDB container using docker compose
  ansible.builtin.shell:
    cmd: "docker compose -f /home/ubuntu/yolo/docker-compose.yaml up -d app-mongo"
    chdir: /home/ubuntu/yolo
  become: yes
  become_user: ubuntu

- name: Wait for MongoDB service to be healthy
  ansible.builtin.shell:
    cmd: "docker inspect --format='{% raw %}{{.State.Health.Status}}{% endraw %}' app-mongo"
    chdir: /home/ubuntu/yolo
  register: mongo_health_check
  until: mongo_health_check.stdout == 'healthy'
  retries: 30
  delay: 10
  become: yes
  become_user: ubuntu
