---
- name: Copy docker-compose.yaml to the EC2 instance
  ansible.builtin.template:
    src: "{{ lookup('env', 'PWD') }}/docker-compose.yaml.j2"
    dest: /home/ubuntu/yolo/docker-compose.yaml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: yes

- name: Pull MongoDB image
  ansible.builtin.shell:
    cmd: "docker pull mongo:4.4"
  become: yes
  become_user: ubuntu

- name: Start MongoDB container using docker compose
  ansible.builtin.shell:
    cmd: "docker compose -f /home/ubuntu/yolo/docker-compose.yaml up -d app-mongo"
    chdir: /home/ubuntu/yolo
  become: yes
  become_user: ubuntu

- name: Wait for MongoDB container to be running
  ansible.builtin.shell:
    cmd: "docker ps --filter 'name=app-mongo' --format '{% raw %}{{.Status}}{% endraw %}'"
    chdir: /home/ubuntu/yolo
  register: mongo_status_check
  until: "'Up' in mongo_status_check.stdout"
  retries: 10
  delay: 5
  become: yes
  become_user: ubuntu

- name: Wait for MongoDB port to be available
  ansible.builtin.wait_for:
    host: localhost
    port: 27017
    timeout: 120
    delay: 10

- name: Check MongoDB logs for any errors
  ansible.builtin.shell:
    cmd: "docker logs app-mongo --tail 20"
  register: mongo_logs
  become: yes
  become_user: ubuntu

- name: Display MongoDB logs
  ansible.builtin.debug:
    var: mongo_logs.stdout_lines

- name: Test MongoDB connection
  ansible.builtin.shell:
    cmd: "docker exec app-mongo mongosh --eval 'db.adminCommand(\"ping\")'"
  register: mongo_ping_test
  retries: 10
  delay: 10
  until: mongo_ping_test.rc == 0
  become: yes
  become_user: ubuntu
