---
- name: Build backend Docker image
  community.docker.docker_image:
    name: timthoithi100/yolo-backend
    tag: 1.0.0
    build:
      path: "{{ app_base_path }}/backend"
    source: build
    state: present
  tags:
    - build_backend

- name: Run backend Docker container
  community.docker.docker_container:
    name: yolo-backend-container
    image: timthoithi100/yolo-backend:1.0.0
    ports:
      - "{{ backend_port }}:5000"
    env:
      MONGO_URI: "mongodb://{{ mongo_container_name }}:27017/{{ mongo_db_name }}"
    networks:
      - name: "{{ docker_network_name }}"
    state: started
    restart_policy: always
    comparisons:
      image: strict
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  tags:
    - run_backend