---
- name: Start Frontend container using docker compose command
  ansible.builtin.shell:
    cmd: "docker ps --filter 'name=tim-client' --format '{% raw %}{{.Status}}{% endraw %}'"
    chdir: /home/ubuntu/yolo
  become: yes
  become_user: ubuntu

- name: Verify Frontend container is running (via docker ps)
  ansible.builtin.shell:
    cmd: "docker ps --filter 'name=tim-client' --format '{{.Status}}'"
    chdir: /home/ubuntu/yolo
  register: frontend_status_check
  until: "'Up' in frontend_status_check.stdout"
  retries: 12
  delay: 5
  become: yes
  become_user: ubuntu
