---
- name: Create custom Docker network for application
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    driver: bridge
    attachable: yes
    ipam_config:
      - subnet: "{{ docker_network_subnet }}"
        ip_range: "{{ docker_network_ip_range }}"
  tags:
    - network

- name: Create Docker volume for MongoDB persistence
  community.docker.docker_volume:
    name: "{{ mongo_volume_name }}"
    driver: local
  tags:
    - mongo_volume
