---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common dependencies
  ansible.builtin.apt:
    name:
      - git
      - docker.io
      - docker-compose
      - python3-pip
    state: present

- name: Ensure pip is installed for docker-py
  ansible.builtin.pip:
    name: pip
    state: latest

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker

- name: Add vagrant user to docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes
