---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common dependencies
  ansible.builtin.apt:
    name:
      - git
      - docker.io
      - docker-compose
      - python3-pip
    state: present
