---
- name: Build frontend Docker image
  community.docker.docker_image:
    name: timthoithi100/yolo-client
    tag: 1.0.0
    build:
      path: "{{ app_base_path }}/client"
      args:
        REACT_APP_API_URL: "http://yolo-backend-container:5000"
    source: build
    state: present
  tags:
    - build_frontend

- name: Run frontend Docker container
  community.docker.docker_container:
    name: yolo-frontend-container
    image: timthoithi100/yolo-client:1.0.0
    ports:
      - "{{ frontend_port }}:3000"
    networks:
      - name: "{{ docker_network_name }}"
    state: started
    restart_policy: always
    comparisons:
      image: strict
  tags:
    - run_frontend